#!/usr/bin/env python3
"""Run a test tier (docs/testing/efficiency-review.md, "Which command when").

Usage: run_tiers.py {fast|changed|full} [--base REF] [--no-diagnose] [-- pytest args...]
       run_tiers.py slow-list REPORT.xml [--threshold SECONDS]

- fast: every test not marked `slow` (tests/slow_tests.txt). Safety tests are never marked slow.
- changed: fast, plus every test, slow ones included, in the files scripts/select_tests.py maps the
  change to. When the selector cannot map the change, this is the full suite.
- full: the whole suite, as CI runs it.
- slow-list: rewrite tests/slow_tests.txt from a JUnit report of a full run (`pytest --junitxml=...`):
  every test function with a case taking THRESHOLD seconds or more (default 0.5), safety tests excepted.

Runs are parallel (pytest-xdist, `-n auto`) unless the pytest args choose: `-- -n 0` runs serially,
`-- -n 8` uses eight workers. CI runs the suite serially.

When a run fails, the files that failed are run again in full (their slow tests too), serially and with
verbose output, so a broad failure comes back with the narrower tests of the same area next to it. Use
--no-diagnose to skip that. The diagnosis run never changes the exit code.
"""

import argparse
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET  # noqa: S405 - only pytest's own JUnit reports are parsed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT / "scripts"), str(ROOT / "tests")]

import select_tests  # noqa: E402
import tier_marks  # noqa: E402

SLOW_HEADER = """\
# Test functions outside the fast tier: scripts/test-fast leaves them out, every other tier runs them.
# Generated by `scripts/run_tiers.py slow-list REPORT.xml` from a timed full run; see tests/tier_marks.py.
# Only tier_marks.SLOW_ELIGIBLE files may appear, and no test matching SAFETY_WORDS: the rest is safety.
"""


def parallel(extra: list[str]) -> list[str]:
    """`-n auto`, unless the caller's pytest args already pick a worker count or turn xdist off."""
    chosen = any(arg in ("-n", "--numprocesses", "no:xdist") or arg.startswith(("-n", "--numprocesses="))
                 for arg in extra)
    return [] if chosen else ["-n", "auto"]


def pytest(args: list[str]) -> tuple[int, set[str]]:
    """Run pytest; return its exit code and the test files with a failed or erroring test."""
    with tempfile.TemporaryDirectory(prefix="hz-tiers") as tmp:
        report = Path(tmp) / "junit.xml"
        cmd = [sys.executable, "-m", "pytest", *args]
        print("+ " + " ".join(cmd[1:]), file=sys.stderr, flush=True)
        code = subprocess.run([*cmd, f"--junitxml={report}"], cwd=ROOT, check=False).returncode
        return code, {nodeid.partition("::")[0] for nodeid, _, bad in cases(report) if bad}


def cases(report: Path) -> list[tuple[str, float, bool]]:
    """(node ID, seconds, failed or errored) for each test case in a JUnit report."""
    try:
        root = ET.parse(report).getroot()  # noqa: S314 - a report pytest just wrote
    except (OSError, ET.ParseError):
        return []
    out: list[tuple[str, float, bool]] = []
    for case in root.iter("testcase"):
        parts = (case.get("classname") or "").split(".")     # tests.test_x[.Class]
        for i in range(len(parts), 0, -1):
            path = ROOT.joinpath(*parts[:i]).with_suffix(".py")
            if path.is_file():
                nodeid = "::".join([str(path.relative_to(ROOT)), *parts[i:], case.get("name") or ""])
                bad = case.find("failure") is not None or case.find("error") is not None
                out.append((nodeid, float(case.get("time") or 0), bad))
                break
    return out


def slow_list(report: Path, threshold: float) -> int:
    rows = cases(report)
    if not rows:
        print(f"no test cases in {report}", file=sys.stderr)
        return 2
    slowest: dict[str, float] = {}
    for nodeid, seconds, _ in rows:
        name = tier_marks.function_id(nodeid)
        slowest[name] = max(slowest.get(name, 0.0), seconds)
    names = sorted(n for n, s in slowest.items() if s >= threshold and not tier_marks.is_safety(n))
    tier_marks.SLOW_LIST.write_text(SLOW_HEADER + "".join(f"{n}\n" for n in names), encoding="utf-8")
    print(f"{len(names)} slow test functions written to {tier_marks.SLOW_LIST.relative_to(ROOT)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("tier", choices=["fast", "changed", "full", "slow-list"])
    ap.add_argument("report", nargs="?", type=Path, help="slow-list: the JUnit report of a full run")
    ap.add_argument("--threshold", type=float, default=0.5, help="slow-list: seconds (default 0.5)")
    ap.add_argument("--base", default="origin/main", help="changed: diff base (default: origin/main)")
    ap.add_argument("--no-diagnose", action="store_true", help="do not rerun failing files in full")
    args, extra = ap.parse_known_args(argv)
    extra = [arg for arg in extra if arg != "--"]
    workers = parallel(extra)

    if args.tier == "slow-list":
        if args.report is None:
            ap.error("slow-list needs a JUnit report")
        return slow_list(args.report, args.threshold)
    if args.report is not None:
        extra.insert(0, str(args.report))       # a bare path after the tier is a pytest argument

    if args.tier == "full":
        runs = [["-q", *workers, *extra]]
    elif args.tier == "fast":
        runs = [["-q", *workers, "-m", "not slow", *extra]]
    else:
        try:
            files = select_tests.select(select_tests.changed_files(args.base), explain=True)
        except select_tests.Full as exc:
            print(f"full suite: {exc}", file=sys.stderr)
            runs = [["-q", *workers, *extra]]
        else:
            print(f"selected {len(files)} test file(s) for the change", file=sys.stderr)
            runs = [["-q", *workers, "-m", "not slow", *extra]]
            if files:                      # what the fast run left out of the selected files
                runs.append(["-q", *workers, "-m", "slow", *extra, *files])

    code = 0
    failed: set[str] = set()
    for run in runs:
        rc, files = pytest(run)
        if rc == 5 and "slow" in run and "not slow" not in run:
            rc = 0                         # the selected files have no slow tests
        failed |= files
        code = code or rc
    if code != 0 and failed and not args.no_diagnose:
        print(f"diagnosis: rerunning {len(failed)} failing file(s) in full", file=sys.stderr)
        serial = [] if workers or "no:xdist" in extra else ["-n", "0"]     # the last -n wins
        pytest(["-rfE", "-v", "--no-header", *extra, *serial, *sorted(failed)])
    return code


if __name__ == "__main__":
    sys.exit(main())
